### ISSUE TITLE
Setup Script missing from repo and dead links.

### ISSUE THREAD

**Issue by yassin-taskin** [dscarvalho/easyesa#2]
Hi. i wanted to setup easy esa. In the description it says to run
$./setup_all.sh
however there is no script with that name in the repo. I tried downloading the distribution under
http://labcores.ppgi.ufrj.br/easyesa/files/easyesa_dist.7z
but it gives me a 404 not found error. I fact every link in the doc to labcore gives me that error.
Could you put the scripts necessary to setup  into the repository?

**Comment by dscarvalho** [comment]
Dear Yassin,

The links to the distribution files were restored.
Thank you for bringing this issue to my attention.

The setup_all.sh script can be found in the distribution package.
