### ISSUE TITLE
Results using this implementation not matching with the results in original ESA paper

### ISSUE THREAD

**Issue by diviya97** [dscarvalho/easyesa#3]
I tried your implementation to compute the spearman's coefficient for wordsim353 dataset. But your results give a correlation of 0.643 whereas in the original paper 'Computing Semantic Relatedness using Wikipedia-based Explicit Semantic Analysis' it is reported to be 0.75. Can anyone explain why is it low for this implementation

**Comment by dscarvalho** [comment]
The EasyESA implementation is not based on the implementation of the original paper, but in the wikiprep-esa implementation from Çağatay Çallı, which was further changed to focus on ease of operation and computational efficiency/speed. We thus make no claims on replicating the results of the original paper. In fact, the representation may not be compatible dimension-wise with the original paper.
More importantly, have you used the same data set of the original paper (the Wikipedia 2006 database dump)? EasyESA uses the Wikipedia 2013 dump as default, which pretty much guarantees the results will be different from the original paper.
