### ISSUE TITLE
error occurs when I try to start mongodb

### ISSUE THREAD

**Issue by snapev** [dscarvalho/easyesa#8]
I download mongodb 3.0.15 and start mongodb  following the steps from 5.1,however,it shows:
 [initandlisten] exception in initAndListen: 28574 Cannot start server. Detected data files in /data/db created by storage engine 'wiredTiger'. The configured storage engine is 'mmapv1'., terminating

So I try to fix it with ''--storageEngine wiredTiger ",however it showes :
I STORAGE  [initandlisten] exception in initAndListen: 13111 wrong type for field (ns) 10 != 2, terminating

could you help me to deal with it?thanks.

**Comment by dscarvalho** [comment]
I tested all the steps from 5.1 on 2 different computers (Ubuntu 18.04 and Mint 18.1) and it worked fine.
The first error you informed should not happen on mongodb 3.0.15. Maybe you are using a different version than the intended one. It is good to check your PATH. Try also the standalone version (tgz).
Could you inform me the OS, version, and java version? Maybe I can find something.

Best regards.

**Comment by snapev** [comment]
> I tested all the steps from 5.1 on 2 different computers (Ubuntu 18.04 and Mint 18.1) and it worked fine.
> The first error you informed should not happen on mongodb 3.0.15. Maybe you are using a different version than the intended one. It is good to check your PATH. Try also the standalone version (tgz).
> Could you inform me the OS, version, and java version? Maybe I can find something.
> 
> Best regards.

I reinstall MongoDB and it works!Thanks a lot!!!!!!!!!!!!
